### WEEK 3 ASSESSMENT

In [1]:
# Import packages
import os

import pandas as pd
import numpy as np

from sklearn.linear_model import ElasticNetCV, ElasticNet

from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
############################### FUNCTIONS ############################

#import helper functions
from fn_helpers import fn_print_coefficients, fn_plot_predictions

#creates linear splines of a variable
def fn_tosplines(varname,x):
#takes a feature name and the values of that feature

    #split feature into percentiles 
    ptiles = np.percentile(x,5*(1+np.arange(20)))
#     print(ptiles)

    #create dataframe which contains the original variable and its original values
    df_ptiles = pd.DataFrame({var: x})

    #now add splines
    for idx, ptile in enumerate(ptiles):
        #NOTE: spline variable is max(0, x - value of knot)
        df_ptiles[var + '_' + str(idx)] = np.maximum(0, x - ptiles[idx])
    return [df_ptiles, ptiles]

def fn_MAE(actuals, predictions):
#     return np.round(np.mean(np.abs(predictions - actuals)))
    return (np.mean(np.abs(predictions - actuals)))

Starting from importing the Ames house price data with pandas (read csv)

In [3]:
# Set directories and paths
print(os.getcwd())
dirRawData = "../input/"
dirPData   = "../PData/"
dirPOutput = "../POutput/"

/Users/alexandrebornerand/Dropbox/AML/Projects/AmesHousing/PCode

In [4]:
############################ Load and read data ######################
# Using the dictionary below (ames_dtypes), use the read_csv function in Pandas to read AmesHousing.txt
# The name of the dataframe you create should be df_all
# Inspect the top few lines to make sure they look sensible
# Note that the column names contain . to separate words and they contain capitals, e.g. Lot.Frontage. Change all column names so that capitals are replaced with lower case and periods (.) are replaced with underscores (_). One way to do this is
# Use sub from the re package to replace . with underscore (_) in all column names
# Use the .lower method on each string to change all letters to lower case

ames_dtypes = {'Order': np.int64,
             'PID': np.int64,
             'MS.SubClass': np.object,
             'MS.Zoning': np.object,
             'Lot.Frontage': np.float64,
             'Lot.Area': np.float64,
             'Street': np.object, 
             'Alley': np.object, 
             'Lot.Shape': np.object, 
             'Land.Contour': np.object,  
             'Lot.Config': np.object,
             'Land.Slope': np.object,
             'Neighborhood': np.object,
             'Condition.1': np.object,
             'Condition.2': np.object,
             'Bldg.Type': np.object,
             'House.Style': np.object,
             'Overall.Qual': np.float64,
             'Overall.Cond': np.float64,
             'Year.Built': np.float64,
             'Year.Remod.Add': np.float64,
             'Roof.Style': np.object,
             'Roof.Matl': np.object,
             'Exterior.1st': np.object,
             'Exterior.2nd': np.object,
             'Mas.Vnr.Type': np.object,
             'Mas.Vnr.Area': np.float64,
             'Exter.Qual': np.object,
             'Exter.Cond': np.object,
             'Foundation': np.object, 
             'Bsmt.Qual': np.object,
             'Bsmt.Cond': np.object,
             'Bsmt.Exposure': np.object,
             'BsmtFin.Type.1': np.object,
             'BsmtFin.SF.1': np.float64,
             'BsmtFin.Type.2': np.object,
             'BsmtFin.SF.2': np.float64,
             'Bsmt.Unf.SF': np.float64,
             'Total.Bsmt.SF': np.float64,
             'Heating': np.object,
             'Heating.QC': np.object,
             'Central.Air': np.object,
             'Electrical': np.object,
             'X1st.Flr.SF': np.float64,
             'X2nd.Flr.SF': np.float64,
             'Low.Qual.Fin.SF': np.float64,
             'Gr.Liv.Area': np.float64, 
             'Bsmt.Full.Bath': np.float64,
             'Bsmt.Half.Bath': np.float64,
             'Full.Bath': np.float64,
             'Half.Bath': np.float64,
             'Bedroom.AbvGr': np.float64,
             'Kitchen.AbvGr': np.float64,
             'Kitchen.Qual': np.object,
             'TotRms.AbvGrd': np.float64, 
             'Functional': np.object, 
             'Fireplaces': np.float64, 
             'Fireplace.Qu': np.object,
             'Garage.Type': np.object, 
             'Garage.Yr.Blt': np.float64,
             'Garage.Finish': np.object,
             'Garage.Cars': np.float64,
             'Garage.Area': np.float64, 
             'Garage.Qual': np.object, 
             'Garage.Cond': np.object, 
             'Paved.Drive': np.object,
             'Wood.Deck.SF': np.float64,
             'Open.Porch.SF': np.float64,
             'Enclosed.Porch': np.float64, 
             'X3Ssn.Porch': np.float64,
             'Screen.Porch': np.float64,
             'Pool.Area': np.float64,
             'Fence': np.object,
             'Misc.Feature': np.object,
             'Misc.Val': np.float64,
             'Mo.Sold': np.float64, 
             'Yr.Sold': np.float64,
             'Sale.Type': np.object,
             'Sale.Condition': np.object,
             'SalePrice': np.float64}
    

#default seperator is comma, but data is seperated with spaces so change sep, set dtype as prev. defined dict
df_all = pd.read_csv(dirRawData+'AmesHousing.txt',sep=' ', dtype = ames_dtypes, na_values = 'NA')
df_all.head() #inspect at first few rows

,Order,PID,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,...,Screen.Porch,Pool.Area,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,1,526301100,MS_20,RL,141.0,31770.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,5.0,2010.0,WD,Normal,215000.0
1,2,526350040,MS_20,RH,80.0,11622.0,Pave,DoesNotHaveOne,Reg,Lvl,...,120.0,0.0,MnPrv,DoesNotHaveOne,0.0,6.0,2010.0,WD,Normal,105000.0
2,3,526351010,MS_20,RL,81.0,14267.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,12500.0,6.0,2010.0,WD,Normal,172000.0
3,4,526353030,MS_20,RL,93.0,11160.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2010.0,WD,Normal,244000.0
4,5,527105010,MS_60,RL,74.0,13830.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,MnPrv,DoesNotHaveOne,0.0,3.0,2010.0,WD,Normal,189900.0

In [5]:
# Note that the column names contain . to separate words and they contain capitals, e.g. Lot.Frontage. 
# Change all column names so that capitals are replaced with lower case and periods (.) are replaced with 
# underscores (_). One way to do this is:
# Use str.replace from the pandas package to replace . with underscore (_) in all column names
# Use the .lower method on each string to change all letters to lower case


#df_all.columns is an index, diff to work with so let's work with values of index
columns = df_all.columns.values
#write a function to replace . with _ and convert string chars to lowercase
# test = "This.Is.A.Test" # to test function
def convert(colname):
    #replace '.' with '_'
    colname = colname.replace('.','_')
    colname = colname.lower() #change to lower case
    return colname
#map is an iterator and returns values one at a time, so must force it into a list
columns=list(map(convert, columns))
df_all.columns = columns #assign df_all.columns to revised columns
df_all.tail(10) #inspect first few rows

,order,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,screen_porch,pool_area,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice
2920,2921,923228310,MS_160,RM,21.0,1894.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Abnorml,71000.0
2921,2922,923229110,MS_90,RL,55.0,12640.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Normal,150900.0
2922,2923,923230040,MS_90,RL,63.0,9297.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Family,188000.0
2923,2924,923250060,MS_20,RL,80.0,17400.0,Pave,DoesNotHaveOne,Reg,Low,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,5.0,2006.0,WD,Normal,160000.0
2924,2925,923251180,MS_20,RL,160.0,20000.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,9.0,2006.0,WD,Abnorml,131000.0
2925,2926,923275080,MS_80,RL,37.0,7937.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,GdPrv,DoesNotHaveOne,0.0,3.0,2006.0,WD,Normal,142500.0
2926,2927,923276100,MS_20,RL,NaN,8885.0,Pave,DoesNotHaveOne,IR1,Low,...,0.0,0.0,MnPrv,DoesNotHaveOne,0.0,6.0,2006.0,WD,Normal,131000.0
2927,2928,923400125,MS_85,RL,62.0,10441.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,MnPrv,Shed,700.0,7.0,2006.0,WD,Normal,132000.0
2928,2929,924100070,MS_20,RL,77.0,10010.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Normal,170000.0
2929,2930,924151050,MS_60,RL,74.0,9627.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,11.0,2006.0,WD,Normal,188000.0

In [6]:
######################### DATA MANIPULATION ##########################
## declare variables
vars_all = df_all.columns.values
# df_all.shape #double check number of rows matches what expected
var_dep = ['saleprice']
vars_notToUse = ['order','pid']
#create list of independent variables
vars_ind = [var for var in vars_all if var not in (vars_notToUse+var_dep)]
#create list of numeric independent variables
vars_ind_numeric = [var for var in vars_ind if df_all[var].dtype != 'object']
#create list of categorical (independent) variables
vars_ind_categorical = [var for var in vars_ind if df_all[var].dtype == 'object']
# print(len(vars_ind_categorical))

In [7]:
################# Deal with missings and outliers ####################
# Note: should have exactly 2922 examples, test with df_all.shape

In [8]:
print(df_all.shape)
#collapse axis = 0 i.e. sum missing values,
#store as series
srs_missing = df_all.isnull().sum(axis=0) 
print(srs_missing[srs_missing>0]) #show which features have missing values

(2930, 80)
lot_frontage      490
mas_vnr_area       23
bsmtfin_sf_1        1
bsmtfin_sf_2        1
bsmt_unf_sf         1
total_bsmt_sf       1
bsmt_full_bath      2
bsmt_half_bath      2
garage_yr_blt     159
garage_cars         1
garage_area         1
dtype: int64

In [9]:
### REPLACE NaNs with non-NaN means if many missing values

In [10]:
# if only a few missing, drop examples with missing values

In [11]:
#store in list the variables which have more than 20 NaN values
vars_to_replace = [var for var in df_all if df_all[var].isnull().sum(axis=0) > 20]

In [12]:
#calculate their NaN mean (mean excluding NaNs)
means_to_replace = [np.nanmean(df_all[var].values) for var in vars_to_replace]

In [13]:
print(vars_to_replace)
print(means_to_replace)

['lot_frontage', 'mas_vnr_area', 'garage_yr_blt']
[69.22459016393442, 101.8968008255934, 1978.1324431613136]

In [14]:
###REPLACE missing values of vars_to_replace with the mean of the non missing values

In [15]:
df_temp=df_all[vars_to_replace].copy()
for var in vars_to_replace:
    i=0
    temp_nanmean = means_to_replace[vars_to_replace.index(var)]
    while i<len(df_temp[var]):
        if np.isnan(df_temp[var].iloc[i]):
            #then replace with mean of non-missing values
            df_temp[var].iloc[i]=temp_nanmean
        i+=1
df_all[vars_to_replace] = df_temp
# df_all.head(100) #just to double check NaNs have been changed

In [16]:
print(df_all.shape)
#collapse axis = 0 i.e. sum missing values,
#store as series
srs_missing = df_all.isnull().sum(axis=0) 
print(srs_missing[srs_missing>0]) #show which features have missing values

(2930, 80)
bsmtfin_sf_1      1
bsmtfin_sf_2      1
bsmt_unf_sf       1
total_bsmt_sf     1
bsmt_full_bath    2
bsmt_half_bath    2
garage_cars       1
garage_area       1
dtype: int64

In [17]:
### Now drop the examples with few missing values

In [18]:
df_all.dropna(axis=0, how='any', inplace=True)
srs_missing = df_all.isnull().sum(axis=0) 
print(srs_missing[srs_missing>0]) #double check no more nans

Series([], dtype: int64)

In [19]:
### Remove known outliers

In [20]:
#i.e. Remove the 5 examples where gr_liv_area > 4000 and check the number of rows again.

In [21]:
df_all = df_all[df_all['gr_liv_area']<=4000]

In [22]:
df_all.shape

(2922, 80)

In [23]:
df_all.tail(10)

,order,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,screen_porch,pool_area,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice
2920,2921,923228310,MS_160,RM,21.00000,1894.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Abnorml,71000.0
2921,2922,923229110,MS_90,RL,55.00000,12640.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Normal,150900.0
2922,2923,923230040,MS_90,RL,63.00000,9297.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Family,188000.0
2923,2924,923250060,MS_20,RL,80.00000,17400.0,Pave,DoesNotHaveOne,Reg,Low,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,5.0,2006.0,WD,Normal,160000.0
2924,2925,923251180,MS_20,RL,160.00000,20000.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,9.0,2006.0,WD,Abnorml,131000.0
2925,2926,923275080,MS_80,RL,37.00000,7937.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,GdPrv,DoesNotHaveOne,0.0,3.0,2006.0,WD,Normal,142500.0
2926,2927,923276100,MS_20,RL,69.22459,8885.0,Pave,DoesNotHaveOne,IR1,Low,...,0.0,0.0,MnPrv,DoesNotHaveOne,0.0,6.0,2006.0,WD,Normal,131000.0
2927,2928,923400125,MS_85,RL,62.00000,10441.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,MnPrv,Shed,700.0,7.0,2006.0,WD,Normal,132000.0
2928,2929,924100070,MS_20,RL,77.00000,10010.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Normal,170000.0
2929,2930,924151050,MS_60,RL,74.00000,9627.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,11.0,2006.0,WD,Normal,188000.0

In [24]:
## NOTE: Having dropped examples, must reset index to spline will not work
df_all.reset_index(drop=True, inplace=True)
df_all.tail(10)

,order,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,screen_porch,pool_area,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice
2912,2921,923228310,MS_160,RM,21.00000,1894.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Abnorml,71000.0
2913,2922,923229110,MS_90,RL,55.00000,12640.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Normal,150900.0
2914,2923,923230040,MS_90,RL,63.00000,9297.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,7.0,2006.0,WD,Family,188000.0
2915,2924,923250060,MS_20,RL,80.00000,17400.0,Pave,DoesNotHaveOne,Reg,Low,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,5.0,2006.0,WD,Normal,160000.0
2916,2925,923251180,MS_20,RL,160.00000,20000.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,9.0,2006.0,WD,Abnorml,131000.0
2917,2926,923275080,MS_80,RL,37.00000,7937.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,0.0,GdPrv,DoesNotHaveOne,0.0,3.0,2006.0,WD,Normal,142500.0
2918,2927,923276100,MS_20,RL,69.22459,8885.0,Pave,DoesNotHaveOne,IR1,Low,...,0.0,0.0,MnPrv,DoesNotHaveOne,0.0,6.0,2006.0,WD,Normal,131000.0
2919,2928,923400125,MS_85,RL,62.00000,10441.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,MnPrv,Shed,700.0,7.0,2006.0,WD,Normal,132000.0
2920,2929,924100070,MS_20,RL,77.00000,10010.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2006.0,WD,Normal,170000.0
2921,2930,924151050,MS_60,RL,74.00000,9627.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,11.0,2006.0,WD,Normal,188000.0

In [25]:
######################## CREATE FOLD VARIABLE ########################

#create instance of random num generator with seed 2018
rng = np.random.RandomState(seed=2018)
# randint(low, high=None, size=None, dtype='l')
#generate as many random ints (in range [0,10]) as there are examples
fold = rng.randint(0,10, len(df_all))
#append to df_all
df_all['fold'] = fold
# df_all_onehot['fold'] = fold
df_all.head(10)

,order,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,pool_area,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice,fold
0,1,526301100,MS_20,RL,141.0,31770.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,5.0,2010.0,WD,Normal,215000.0,6
1,2,526350040,MS_20,RH,80.0,11622.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,MnPrv,DoesNotHaveOne,0.0,6.0,2010.0,WD,Normal,105000.0,2
2,3,526351010,MS_20,RL,81.0,14267.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,12500.0,6.0,2010.0,WD,Normal,172000.0,9
3,4,526353030,MS_20,RL,93.0,11160.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2010.0,WD,Normal,244000.0,5
4,5,527105010,MS_60,RL,74.0,13830.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,MnPrv,DoesNotHaveOne,0.0,3.0,2010.0,WD,Normal,189900.0,4
5,6,527105030,MS_60,RL,78.0,9978.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,6.0,2010.0,WD,Normal,195500.0,6
6,7,527127150,MS_120,RL,41.0,4920.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,4.0,2010.0,WD,Normal,213500.0,9
7,8,527145080,MS_120,RL,43.0,5005.0,Pave,DoesNotHaveOne,IR1,HLS,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,1.0,2010.0,WD,Normal,191500.0,9
8,9,527146030,MS_120,RL,39.0,5389.0,Pave,DoesNotHaveOne,IR1,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,3.0,2010.0,WD,Normal,236500.0,7
9,10,527162130,MS_60,RL,60.0,7500.0,Pave,DoesNotHaveOne,Reg,Lvl,...,0.0,DoesNotHaveOne,DoesNotHaveOne,0.0,6.0,2010.0,WD,Normal,189000.0,9

In [26]:
################### ONE-HOT CATEGORICAL VARS ########################

In [27]:
# df_all[vars_ind_categorical].nunique() #show cardinality of each categorical variable
#cardinality not too high so can simply one-hot all cat variables

#start with empty list
vars_ind_onehot = []

#create copy to work with
df_all_onehot = df_all.copy()

for col in vars_ind_categorical:
#     print(col)
    
    # use pd.get_dummies on  df_all[col] 
    df_oh = pd.get_dummies(df_all[col], drop_first=False)
    
    # Find the column name of the most frequent category
    col_mostFreq =  df_oh.sum(axis=0).idxmax() 
    
    # Drop the column of the most frequent category
    df_oh = df_oh.drop(col_mostFreq, axis=1, inplace=False)
        
    # Rename the columns to have the original variable name as a prefix
    oh_names = col+'_'+df_oh.columns
    df_oh.columns = oh_names
    
    df_all_onehot = pd.concat([df_all_onehot, df_oh], axis = 1, sort = False)

    del df_all_onehot[col]
    vars_ind_onehot.extend(oh_names)
df_all_onehot.head()

,order,pid,lot_frontage,lot_area,overall_qual,overall_cond,year_built,year_remod_add,mas_vnr_area,bsmtfin_sf_1,...,misc_feature_Shed,sale_type_COD,sale_type_CWD,sale_type_ConLD,sale_type_New,sale_condition_Abnorml,sale_condition_AdjLand,sale_condition_Alloca,sale_condition_Family,sale_condition_Partial
0,1,526301100,141.0,31770.0,6.0,5.0,1960.0,1960.0,112.0,639.0,...,0,0,0,0,0,0,0,0,0,0
1,2,526350040,80.0,11622.0,5.0,6.0,1961.0,1961.0,0.0,468.0,...,0,0,0,0,0,0,0,0,0,0
2,3,526351010,81.0,14267.0,6.0,6.0,1958.0,1958.0,108.0,923.0,...,0,0,0,0,0,0,0,0,0,0
3,4,526353030,93.0,11160.0,7.0,5.0,1968.0,1968.0,0.0,1065.0,...,0,0,0,0,0,0,0,0,0,0
4,5,527105010,74.0,13830.0,5.0,5.0,1997.0,1998.0,0.0,791.0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# vars_ind_onehot

In [29]:
#################### ADDING SPLINED FEATURES #########################

In [30]:
# For at least some of the numerical ind variables, add linear spline features

In [31]:
######Â CONSIDER NOT USING ALL NUMERICAL IND VARIABLES

In [32]:
# ####EITHER EXCLUDE VARS CHOSEN BY PROF
# vars_toUse = vars_ind_numeric
# temp = ['bsmtfin_sf_1', 'bsmtfin_sf_2', 'bsmt_unf_sf',
#         'bsmt_full_bath', 'bsmt_half_bath',
#         'garage_cars',
#         'bedroom_abvgr', 'kitchen_abvgr',
#         'full_bath', 'half_bath',
#         'x1st_flr_sf', 'x2nd_flr_sf', 'low_qual_fin_sf',
#         'total_bsmt_sf',
#         'totrms_abvgrd', 'lot_area', 'overall_qual']
# vars_toUse = [var for var in vars_toUse if var not in temp]
# # X = df_all[vars_toUse].values
# # y = df_all[var_dep].values

In [33]:
###Â ALTERNATIVELY CHOSE VARS TO EXCLUDE BY CARDINALITY

In [34]:
# Note that vars with less than 20 unique values will not spline well,
# A solution is not to spline those with cardinality < 20

###check cardinality
# print(df_all[vars_ind_numeric].nunique())
vars_ind_num_exclude = [var for var in vars_ind_numeric if len(df_all[var].unique())<20]

##vars_ind and remove those to be excluded
# print(vars_ind_num_exclude)
vars_ind_num_include = [var for var in vars_ind_numeric if var not in vars_ind_num_exclude]
print(vars_ind_num_include)
# df_all[vars_ind_num_include].nunique()
vars_toUse = vars_ind_num_include

['lot_frontage', 'lot_area', 'year_built', 'year_remod_add', 'mas_vnr_area', 'bsmtfin_sf_1', 'bsmtfin_sf_2', 'bsmt_unf_sf', 'total_bsmt_sf', 'x1st_flr_sf', 'x2nd_flr_sf', 'low_qual_fin_sf', 'gr_liv_area', 'garage_yr_blt', 'garage_area', 'wood_deck_sf', 'open_porch_sf', 'enclosed_porch', 'x3ssn_porch', 'screen_porch', 'misc_val']

In [35]:
# len(vars_ind_num_exclude)

In [36]:
df_temp = df_all_onehot.copy()
print(df_all_onehot.shape)
print(df_temp.shape)
srs_missing = df_temp.isnull().sum(axis=0) 
print(srs_missing[srs_missing>0]) #double check no more nans

(2922, 223)
(2922, 223)
Series([], dtype: int64)

In [37]:
############################## STANDARDISE DATA BEFORE CREATING SPLINES ##############################

In [38]:
######## Recreate train and test data over df_all_onehot
### Separate train and test
idx_train  = np.where(df_all['fold'].isin(np.arange(0,6)))[0]
idx_val    = np.where(df_all['fold'].isin([6,7]))[0]
idx_design = np.where(df_all['fold'].isin(np.arange(0,8)))[0]
idx_test   = np.where(df_all['fold'].isin([8,9]))[0]
print(idx_train.shape)
print(idx_design.shape)
print(idx_test.shape)

df_train = df_all_onehot.iloc[idx_train]
df_val = df_all_onehot.iloc[idx_val]
df_design = df_all_onehot.iloc[idx_design]
df_test = df_all_onehot.iloc[idx_test]
# df_train.head()

#redefine independent variables
vars_ind = vars_ind_numeric+vars_ind_onehot

#define independent variables, excluding those we
vars_x = [var for var in df_all_onehot.columns.values if var not in (var_dep+vars_notToUse)]
vars_x = vars_ind
X_train = df_train[vars_x]
X_val = df_val[vars_x]
X_design = df_design[vars_x]
X_test = df_test[vars_x]
# X = df_all_onehot[vars_x]
y = df_all_onehot['saleprice']



## Standardise
from sklearn.preprocessing import StandardScaler
standardScaler_ = StandardScaler()
standardScaler_.fit(X_design)

X_train = standardScaler_.transform(X_train)
X_val   = standardScaler_.transform(X_val)
X_design= standardScaler_.transform(X_design)
X_test  = standardScaler_.transform(X_test)

(1749,)
(2335,)
(587,)

In [39]:
#iterate over variables which we want to turn into a spline
#append slines to data
for var in vars_toUse: 
    df_ptiles, knots = fn_tosplines(var, df_all_onehot[var].values)
    #drop original variable after having created splines from it
    #as adding back the splines will also add back original var
    df_all_onehot.drop(columns = [var], inplace=True)
    #remove it from list of numeric independent vars for same reason
    vars_ind_numeric.remove(var)
    #append spline columns (for current var) to dataset
    df_all_onehot = pd.concat([df_all_onehot, df_ptiles],axis=1, sort=False)
    vars_ind_numeric.extend(df_ptiles.columns.tolist())

In [40]:
# df_temp.tail(10)

In [41]:
# df_all['misc_val'][df_all['misc_val']>0]

In [42]:
# df_all[['misc_val_{}'.format(i) for i in range(0,20)]].iloc[11]

In [43]:

# vars_ind

In [44]:
srs_missing = df_temp.isnull().sum(axis=0) 
print(srs_missing[srs_missing>0]) #double check no more nans

Series([], dtype: int64)

In [45]:
# df_all.tail(10)

In [46]:
len(df_all)

2922

### Fit a penalised linear regression model using ElasticNetCV and/or ElasticNet from sklearn

In [62]:
l1_ratio = [.1, .5, .7, .9, .95, .99, 1]
# l1_ratio = 1
model = ElasticNetCV(l1_ratio,alphas = [2**num for num in range(-10,15)], cv=10,random_state=2018, selection='cyclic', max_iter=10000)
model.fit(X=X_design, y=y[idx_design])

/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 38008461216.677, tolerance: 1365075185.2841396
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 27316772578.354614, tolerance: 1251536701.140667
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 26803435515.50647, tolerance: 1416890675.829695
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 24353062410.85791, tolerance: 1415109972.2032108
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 25468274216.302856, tolerance: 1325809308.2211244
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 28268934074.41736, tolerance: 1392280565.4771895
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 30166858709.78058, tolerance: 1338386300.2121615
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 29965085768.78076, tolerance: 1324169527.0874443
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 26502352892.364624, tolerance: 1401182918.9214504
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1610672393.1186523, tolerance: 1365075185.2841396
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 20034337355.324463, tolerance: 1365075185.2841396
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3962832342.9699707, tolerance: 1251536701.140667
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 73383782464.85071, tolerance: 1416890675.829695
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 34785439142.63928, tolerance: 1392280565.4771895
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6124163747.394409, tolerance: 1365075185.2841396
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 14458290853.241943, tolerance: 1365075185.2841396
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 26218038468.717407, tolerance: 1416890675.829695
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3779170334.8773193, tolerance: 1392280565.4771895
  tol, rng, random, positive)
/Users/alexandrebornerand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:471: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2478249949.5075684, tolerance: 1365075185.2841396
  tol, rng, random, positive)

ElasticNetCV(alphas=[0.0009765625, 0.001953125, 0.00390625, 0.0078125, 0.015625,
                     0.03125, 0.0625, 0.125, 0.25, 0.5, 1, 2, 4, 8, 16, 32, 64,
                     128, 256, 512, 1024, 2048, 4096, 8192, 16384],
             copy_X=True, cv=10, eps=0.001, fit_intercept=True,
             l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=10000,
             n_alphas=100, n_jobs=None, normalize=False, positive=False,
             precompute='auto', random_state=2018, selection='cyclic',
             tol=0.0001, verbose=0)

In [63]:
# X = df_train[vars_x]

In [64]:
fn_print_coefficients(model)

Learned polynomial for degree 219:
181056.8809 + 684.6063x + 5900.9623x^2 + 11458.2392x^3 + 5132.1135x^4 + 8418.4475x^5 + 1884.5950x^6 + 4696.3928x^7 + 8248.3397x^8 + 468.7781x^9 + -0.0000x^10 + 8880.4312x^11 + 0.0000x^12 + 0.0000x^13 + -556.2940x^14 + 27306.2104x^15 + 719.4594x^16 + -404.9341x^17 + 1129.1654x^18 + 1225.3177x^19 + -3245.1710x^20 + -3239.6738x^21 + 0.0000x^22 + 1736.0454x^23 + 1618.1969x^24 + 2249.1113x^25 + 3516.9754x^26 + 1019.9623x^27 + 365.5895x^28 + 577.0722x^29 + -0.0000x^30 + 2656.8483x^31 + 1157.8033x^32 + 0.0000x^33 + -161.1347x^34 + -568.8673x^35 + -2058.9614x^36 + -2139.3329x^37 + -310.8194x^38 + -0.0000x^39 + 308.2466x^40 + 96.1404x^41 + -0.0000x^42 + -0.0000x^43 + 0.0000x^44 + 36.0731x^45 + -70.1304x^46 + 0.0000x^47 + -1981.9991x^48 + -658.4421x^49 + 538.4073x^50 + -0.0000x^51 + -842.5116x^52 + -300.6051x^53 + -0.0000x^54 + -6.1934x^55 + -0.0000x^56 + 22.1835x^57 + -0.0000x^58 + -159.2937x^59 + 740.9536x^60 + -501.4267x^61 + -323.5688x^62 + 1273.6763x^63 + -778.8429x^64 + -194.6280x^65 + 332.9756x^66 + -1903.7017x^67 + 6.9933x^68 + 415.0464x^69 + 1571.5681x^70 + 120.5487x^71 + -0.0000x^72 + 2578.1286x^73 + -340.0203x^74 + -385.3810x^75 + -62.4340x^76 + 0.0000x^77 + -1069.1269x^78 + 578.0180x^79 + -1342.6525x^80 + 4003.3896x^81 + 4436.8102x^82 + -628.2021x^83 + -7.5012x^84 + 770.7729x^85 + -0.0000x^86 + 2124.5957x^87 + 5212.1501x^88 + -0.0000x^89 + 13.0391x^90 + -1072.0353x^91 + -1478.8212x^92 + 0.0000x^93 + 0.0000x^94 + -952.5369x^95 + -147.1169x^96 + -671.4830x^97 + -877.1770x^98 + -190.4743x^99 + -1549.6495x^100 + -1088.7711x^101 + -876.4595x^102 + 0.0000x^103 + 0.0000x^104 + -0.0000x^105 + -0.0000x^106 + -0.0000x^107 + -0.0000x^108 + -0.0000x^109 + -0.0000x^110 + 40.8547x^111 + -135.8479x^112 + 0.0000x^113 + 2318.3196x^114 + 0.0000x^115 + -634.4389x^116 + 0.0000x^117 + -0.0000x^118 + 164.7078x^119 + -67.5037x^120 + -0.0000x^121 + 0.0000x^122 + -0.0000x^123 + -704.0227x^124 + 112.0949x^125 + -147.6876x^126 + -696.8847x^127 + 0.0000x^128 + -1386.8734x^129 + 378.8457x^130 + 0.0000x^131 + -56.7869x^132 + -1306.7542x^133 + -2540.1552x^134 + 232.0292x^135 + 5444.8079x^136 + 0.0000x^137 + 774.9544x^138 + -0.0000x^139 + -350.9355x^140 + 0.0000x^141 + -0.0000x^142 + -211.7282x^143 + 0.0000x^144 + 334.5134x^145 + 1551.0478x^146 + 4926.8165x^147 + 317.1071x^148 + -90.1224x^149 + 1024.8109x^150 + 0.0000x^151 + -0.0000x^152 + 1216.7689x^153 + 35.6378x^154 + 4568.0677x^155 + -0.0000x^156 + -0.0000x^157 + -191.7891x^158 + 71.2507x^159 + -1275.3731x^160 + -1087.8690x^161 + -0.0000x^162 + 1041.3750x^163 + -0.0000x^164 + 34.8342x^165 + 1610.2003x^166 + -0.0000x^167 + -0.0000x^168 + -70.3518x^169 + -358.5077x^170 + -0.0000x^171 + -1076.3804x^172 + 0.0000x^173 + -0.0000x^174 + 0.0000x^175 + 5017.8808x^176 + 15.6443x^177 + 436.9598x^178 + -2505.0786x^179 + -1461.4283x^180 + -1473.7440x^181 + -1171.9640x^182 + 225.2694x^183 + -676.5937x^184 + 0.0000x^185 + 0.0000x^186 + -293.4330x^187 + -177.9956x^188 + -274.4637x^189 + 347.7613x^190 + -319.5648x^191 + 326.5549x^192 + 1137.4091x^193 + 0.0000x^194 + 0.0000x^195 + -999.1912x^196 + 0.0000x^197 + 0.0000x^198 + 516.0710x^199 + 0.0000x^200 + -58.3024x^201 + -48.0507x^202 + -0.0000x^203 + 0.0000x^204 + -245.7276x^205 + -54.9154x^206 + 484.4521x^207 + 99.7743x^208 + -95.4855x^209 + -0.0000x^210 + -36.1522x^211 + -0.0000x^212 + 167.5160x^213 + 2633.6778x^214 + -2914.3012x^215 + 507.1665x^216 + 0.0000x^217 + -217.9808x^218 + 314.3575x^219

In [65]:
train_preds = model.predict(X_train)
val_preds = model.predict(X_val)
design_preds = model.predict(X_design)
test_preds = model.predict(X_test)

In [66]:
# mean absolute error in predictions

train_error = fn_MAE(y[idx_train], train_preds) 
validation_error = fn_MAE(y[idx_val], val_preds)
design_error = fn_MAE(y[idx_design], design_preds)


test_error = fn_MAE(y[idx_test], test_preds)

# on train data
print('train error', train_error)
print('\n')

# on validation data
print('validation naive (null) model', fn_MAE(np.median(y[idx_val]),  y[idx_val]))
print('validation error', validation_error)
print('\n')

# on design data
print('design (train + val) error', design_error)
print('\n')

# test data, null model
print('test naive (null) model', fn_MAE(np.median(y[idx_test]), y[idx_test]))
print('test error', test_error)

print('differnece between test and non-test error', test_error-design_error)

train error 13691.194934640767


validation naive (null) model 56596.921501706485
validation error 13140.934320247969


design (train + val) error 13553.099551328502


test naive (null) model 52206.85178875639
test error 14629.374858371086
differnece between test and non-test error 1076.2753070425842

In [52]:
# fig, axes = plt.subplots(3, 1, figsize=[12,24], sharex=True, sharey=True)
# axes[0].scatter(train_preds, y[idx_train], s = 1, alpha = 0.3)
# axes[0].set_title('Training data')
# axes[0].axes.xaxis.set_ticklabels([])
# axes[0].axes.yaxis.set_ticklabels([])
# axes[0].set_xlabel('predicted')
# axes[0].set_ylabel('actual')

# axes[1].scatter(val_preds, y[idx_val], s = 1)
# axes[1].set_title('Validation data')
# axes[1].set_xlabel('predicted')
# axes[1].set_ylabel('actual')

# axes[2].scatter(test_preds, y[idx_test], s = 1)
# axes[2].set_title('Test data')
# axes[2].set_xlabel('predicted')
# axes[2].set_ylabel('actual')

In [53]:
# print(len(idx_train))
# print(len(idx_val))
# print(len(idx_design))

In [55]:
# m_log_lambdas = -np.log10(model.alphas_)

# font = {'size': 20}
# plt.rc('font', **font)

# fig = plt.figure(figsize=(10,6))
# ax1 = fig.add_subplot(1, 1, 1)
# ax1.plot(m_log_lambdas, model.mse_path_, ':')
# ax1.plot(m_log_lambdas, model.mse_path_.mean(axis=-1),
#          'k',
#          label='Average across the folds',
#          linewidth=2)

# ax1.axvline(-np.log10(model.alpha_),
#             linestyle='--', 
#             color='k',
#             label='alpha: CV estimate')

# ax1.legend()

# ax1.set_xlabel('-log10(lambda)')
# ax1.set_ylabel('Mean square error')
# ax1.set_title('Mean square error on each fold')
# _ = ax1.axis('tight')

In [56]:
#### regularisation strength chosen
np.log10(model.alpha_)

2.4082399653118496

In [57]:
model.alpha_

256.0

In [58]:
m_log_lambdas

array([-4.21441994, -3.91338994, -3.61235995, -3.31132995, -3.01029996,
       -2.70926996, -2.40823997, -2.10720997, -1.80617997, -1.50514998,
       -1.20411998, -0.90308999, -0.60205999, -0.30103   , -0.        ,
        0.30103   ,  0.60205999,  0.90308999,  1.20411998,  1.50514998,
        1.80617997,  2.10720997,  2.40823997,  2.70926996,  3.01029996])

In [59]:
model.l1_ratio_

1.0

In [74]:
model_En = ElasticNet(alpha=350, l1_ratio=model.l1_ratio_, fit_intercept=True, normalize=False, max_iter=1000, copy_X=True, tol=0.0001, warm_start=False, positive=False, random_state=None, selection='cyclic')
model_En.fit(X=X_design, y=y[idx_design])


train_preds = model_En.predict(X_train)
val_preds = model_En.predict(X_val)
design_preds = model_En.predict(X_design)
test_preds = model_En.predict(X_test)


# mean absolute error in predictions

train_error = fn_MAE(y[idx_train], train_preds) 
validation_error = fn_MAE(y[idx_val], val_preds)
design_error = fn_MAE(y[idx_design], design_preds)


test_error = fn_MAE(y[idx_test], test_preds)

# on train data
print('train error', train_error)
print('\n')

# on validation data
print('validation naive (null) model', fn_MAE(np.median(y[idx_val]),  y[idx_val]))
print('validation error', validation_error)
print('\n')

# on design data
print('design (train + val) error', design_error)
print('\n')

# test data, null model
print('test naive (null) model', fn_MAE(np.median(y[idx_test]), y[idx_test]))
print('test error', test_error)

print('differnece between test and non-test error', test_error-design_error)

train error 13798.54124067273


validation naive (null) model 56596.921501706485
validation error 13251.57434942352


design (train + val) error 13661.272461969507


test naive (null) model 52206.85178875639
test error 14563.701143502685
differnece between test and non-test error 902.428681533178